name = "LeanLCS"
version = "0.1.0"
defaultTargets = ["LeanLCS"]

[[lean_lib]]
name = "LeanLCS"
roots = [
  "LeanLCS", "MathlibExtras", "TopologicalGroups", "TopologicalVectorSpaces",
  "LocallyConvexSpaces", "WebbedSpaces",
]
globs = [
  "LeanLCS", "MainResults",
  "MathlibExtras", "MathlibExtras.+",
  "TopologicalGroups", "TopologicalGroups.+",
  "TopologicalVectorSpaces", "TopologicalVectorSpaces.+",
  "LocallyConvexSpaces", "LocallyConvexSpaces.+",
  "WebbedSpaces", "WebbedSpaces.+",
]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.34.0"
