/-
Copyright (c) 2026 Bastiaan J Braams. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Bastiaan J Braams
-/
module

public import Mathlib.Analysis.LocallyConvex.WithSeminorms
public import TopologicalVectorSpaces.SeminormSummability
public import Mathlib.Analysis.Normed.Group.InfiniteSum
public import Mathlib.Data.Finset.Order

/-!
# Countable seminorms in polynormable spaces

Over any nontrivially normed field, every neighbourhood of zero in a polynormable space contains
the unit ball of a continuous seminorm, so a first-countable polynormable topology is generated
by a sequence of seminorms. The selection results require only a topology, without a chosen
uniformity. The real and complex locally convex corollaries are in
`LocallyConvexSpaces.CountableSeminorms`.

## Main statements

* `PolynormableSpace.exists_continuous_seminorm_ball_subset`.
* `PolynormableSpace.exists_seminormFamily_nat_withSeminorms`: a first-countable polynormable
  space is defined by a sequence of seminorms.
* `PolynormableSpace.exists_directed_withSeminorms`,
  `PolynormableSpace.exists_monotone_withSeminorms`: directed and monotone defining families.
* `WithSeminorms.summable_of_forall_le`: in a complete space defined by a sequence of
  seminorms, a summable scalar bound on the tail for each seminorm gives summability.

## References

* [H. H. Schaefer and M. P. Wolff, *Topological Vector Spaces*][schaefer1999], I §6.1, II §4
-/

public section

open Set Filter

open scoped Topology Pointwise

section Polynormable

variable {𝕜 E : Type*} [NontriviallyNormedField 𝕜] [AddCommGroup E] [Module 𝕜 E]
  [TopologicalSpace E] [PolynormableSpace 𝕜 E]

/-- Every zero neighbourhood in a polynormable space contains the unit ball of a continuous
seminorm. -/
theorem PolynormableSpace.exists_continuous_seminorm_ball_subset {U : Set E}
    (hU : U ∈ 𝓝 (0 : E)) : ∃ p : Seminorm 𝕜 E, Continuous p ∧ p.ball 0 1 ⊆ U :=
  (PolynormableSpace.hasBasis_zero_ball 𝕜 E).mem_iff.mp hU

variable (𝕜 E) in
/-- The topology of a first-countable polynormable space is defined by a sequence of seminorms. -/
theorem PolynormableSpace.exists_seminormFamily_nat_withSeminorms [FirstCountableTopology E] :
    ∃ p : SeminormFamily 𝕜 E ℕ, WithSeminorms p := by
  have : IsTopologicalAddGroup E := PolynormableSpace.isTopologicalAddGroup 𝕜 E
  obtain ⟨b, hb⟩ := (𝓝 (0 : E)).exists_antitone_basis
  have hex (n : ℕ) : ∃ p : Seminorm 𝕜 E, Continuous p ∧ p.ball 0 1 ⊆ b n :=
    PolynormableSpace.exists_continuous_seminorm_ball_subset (hb.mem n)
  choose p hp hpb using hex
  refine ⟨p, SeminormFamily.withSeminorms_of_hasBasis p ⟨fun V ↦ ⟨fun hV ↦ ?_, ?_⟩⟩⟩
  · obtain ⟨n, hn⟩ := hb.mem_iff.mp hV
    exact ⟨(p n).ball 0 1, SeminormFamily.basisSets_singleton_mem p n one_pos, (hpb n).trans hn⟩
  · rintro ⟨U, hU, hUV⟩
    refine mem_of_superset ?_ hUV
    obtain ⟨s, r, hr, rfl⟩ := (SeminormFamily.basisSets_iff p).mp hU
    rw [id, Seminorm.ball_finset_sup_eq_iInter _ _ _ hr]
    exact (Filter.biInter_finset_mem s).2 fun i _ ↦ Seminorm.ball_mem_nhds (hp i) hr

variable (𝕜 E) in
/-- Every polynormable space has a directed defining family of continuous seminorms. -/
theorem PolynormableSpace.exists_directed_withSeminorms :
    ∃ p : SeminormFamily 𝕜 E {p : Seminorm 𝕜 E // Continuous p},
      WithSeminorms p ∧ Directed (· ≤ ·) p := by
  refine ⟨fun p ↦ p.1, PolynormableSpace.withSeminorms 𝕜 E, ?_⟩
  intro p q
  exact ⟨⟨p.1 ⊔ q.1, p.2.max q.2⟩, le_sup_left, le_sup_right⟩

variable (𝕜 E) in
/-- A first-countable polynormable space has a monotone sequence of defining seminorms. -/
theorem PolynormableSpace.exists_monotone_withSeminorms [FirstCountableTopology E] :
    ∃ p : SeminormFamily 𝕜 E ℕ, WithSeminorms p ∧ Monotone p := by
  obtain ⟨p, hp⟩ := PolynormableSpace.exists_seminormFamily_nat_withSeminorms 𝕜 E
  exact ⟨fun n ↦ (Finset.Iic n).sup p, hp.partial_sups,
    fun _ _ h ↦ Finset.sup_mono (Finset.Iic_subset_Iic.mpr h)⟩

end Polynormable

section Summability

variable {𝕜 E : Type*} [NontriviallyNormedField 𝕜] [AddCommGroup E] [Module 𝕜 E]
  [UniformSpace E] [IsUniformAddGroup E] [CompleteSpace E] {p : SeminormFamily 𝕜 E ℕ}

/-- In a complete space whose topology is generated by a sequence of seminorms `p`, a series
`∑ y k` is summable as soon as `p i (y k) ≤ g k` for all `i ≤ k`, where `g` is a summable
sequence of real numbers. -/
theorem WithSeminorms.summable_of_forall_le (hp : WithSeminorms p) {y : ℕ → E} {g : ℕ → ℝ}
    (hg : Summable g) (hy : ∀ k, ∀ i ≤ k, p i (y k) ≤ g k) : Summable y := by
  apply hp.summable_of_forall_summable_seminorm
  intro i
  apply hg.of_norm_bounded_eventually_nat
  filter_upwards [eventually_ge_atTop i] with k hk
  simpa only [Real.norm_eq_abs, abs_of_nonneg (apply_nonneg (p i) (y k))] using hy k i hk

end Summability
