/-
Copyright (c) 2026 Bastiaan J Braams. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Bastiaan J Braams
-/
module

public import Mathlib.Analysis.LocallyConvex.WithSeminorms
public import Mathlib.Topology.Algebra.InfiniteSum.Order

/-!
# Summability controlled by arbitrary families of seminorms

In a complete space whose topology is generated by seminorms `p i`, a family `x j` is
summable if each nonnegative real family `p i (x j)` is summable. Both index types are
arbitrary; no countability or separation assumption is needed. Summability here means
convergence of the net of finite subsums. The condition is sufficient, not necessary.
-/

public section

open Set Filter
open scoped Topology

variable {𝕜 E ι κ : Type*} [NontriviallyNormedField 𝕜] [AddCommGroup E] [Module 𝕜 E]
  [UniformSpace E] [IsUniformAddGroup E] [CompleteSpace E] {p : SeminormFamily 𝕜 E ι}

/-- Absolute summability for each defining seminorm implies summability in a complete
space. Neither the family of seminorms nor the summation index needs to be countable. -/
theorem WithSeminorms.summable_of_forall_summable_seminorm (hp : WithSeminorms p)
    {x : κ → E} (hx : ∀ i, Summable fun j ↦ p i (x j)) : Summable x := by
  classical
  rw [summable_iff_vanishing]
  intro U hU
  obtain ⟨⟨s, r⟩, hr, hsU⟩ := hp.hasBasis_zero_ball.mem_iff.mp hU
  have hr : 0 < r := hr
  have htail (i : ι) := summable_iff_vanishing.mp (hx i)
    (Metric.ball 0 r) (Metric.ball_mem_nhds 0 hr)
  choose t ht using htail
  refine ⟨s.biUnion t, fun u hu ↦ hsU ?_⟩
  rw [Seminorm.mem_ball_zero]
  refine Seminorm.finset_sup_apply_lt hr fun i hi ↦ ?_
  have hdisj : Disjoint u (t i) := Finset.disjoint_left.mpr fun j hj hjt ↦
    Finset.disjoint_left.mp hu hj (Finset.mem_biUnion.mpr ⟨i, hi, hjt⟩)
  have hsum := ht i u hdisj
  rw [mem_ball_zero_iff, Real.norm_eq_abs] at hsum
  exact (Finset.le_sum_of_subadditive (p i) (map_zero (p i)).le
    (map_add_le_add (p i)) u x).trans_lt ((le_abs_self _).trans_lt hsum)
