/-
Copyright (c) 2026 Bastiaan J Braams. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Bastiaan J Braams
-/
module

public import LocallyConvexSpaces.FinalTopology
public import LocallyConvexSpaces.PolarCalculus
public import LocallyConvexSpaces.StrongDualBanachDisk
public import Mathlib.Analysis.LocallyConvex.StrongTopology
public import WebbedSpaces.Criteria

/-!
# The strong dual of a countable hull of metrizable spaces is strictly webbed

Let `F` carry the final locally convex topology of a sequence of linear maps `f n : X n → F` whose
ranges span `F`, where every `X n` is a first-countable topological vector space; for instance let
`F` be an LF space. Then the strong dual of `F` is strictly webbed ([G. Köthe, *Topological Vector
Spaces II*][kothe1979], §35.4.(13)). So De Wilde's closed graph theorem applies to maps into spaces
of distributions.

With `U n` a decreasing basis of neighbourhoods of zero in `X n`, the set of the web for the
indices `m₀, …, m_{k-1}` consists of the functionals that are bounded by one on `f i (U i (m i))`
for all `i < k`. These sets are `ℝ`-convex, balanced and strongly closed. Along a strand, any
sequence `x k` in the sets of the strand is bounded by one on `f i (V i)` for neighbourhoods
`V i ⊆ U i (m i)` of zero, so it lies in the polar of the neighbourhood of zero generated by the
`f i (V i)`, which is a Banach disk (`StrongDual.isBanachDisk_polar_of_mem_nhds`). Köthe's
criteria §35.1.(1) and (2) (`WebbedSpaces.Criteria`) finish the proof.

## Main definitions

* `StrongDual.hullWeb f U`.

## Main statements

* `StrongDual.strictlyWebbedSpace_of_locallyConvexFinalTopology`

## References

* [G. Köthe, *Topological Vector Spaces II*][kothe1979], §35.4.(13)

## Tags

webbed space, strong dual, LF space, distributions
-/

public section

open Set Filter PiNat Bornology

open scoped Topology


variable {𝕜 : Type*} [RCLike 𝕜] {X : ℕ → Type*} {F : Type*}
  [∀ n, AddCommGroup (X n)] [∀ n, Module 𝕜 (X n)] [∀ n, TopologicalSpace (X n)]
  [AddCommGroup F] [Module 𝕜 F] [Module ℝ F] [IsScalarTower ℝ 𝕜 F] [TopologicalSpace F]

namespace StrongDual

/-- The web on the dual of a hull: the set for the indices `m₀, …, m_{k-1}` (newest index at the
head of the list) consists of the functionals bounded by one on `f i (U i (m i))` for `i < k`. -/
@[expose]
def hullWeb (f : ∀ n, X n →ₗ[𝕜] F) (U : ∀ n, ℕ → Set (X n)) : List ℕ → Set (StrongDual 𝕜 F)
  | [] => univ
  | m :: l => hullWeb f U l ∩ polar 𝕜 (f l.length '' U l.length m)

variable (f : ∀ n, X n →ₗ[𝕜] F) (U : ∀ n, ℕ → Set (X n))

omit [∀ n, TopologicalSpace (X n)] [Module ℝ F] [IsScalarTower ℝ 𝕜 F] in
/-- The successors of a set of the web on the dual of a hull. -/
theorem hullWeb_cons (m : ℕ) (l : List ℕ) :
    hullWeb f U (m :: l) = hullWeb f U l ∩ polar 𝕜 (f l.length '' U l.length m) :=
  rfl

omit [∀ n, TopologicalSpace (X n)] [Module ℝ F] [IsScalarTower ℝ 𝕜 F] in
/-- Membership of the sets along a strand of the web on the dual of a hull. -/
theorem mem_hullWeb_res {σ : ℕ → ℕ} {k : ℕ} {φ : StrongDual 𝕜 F} :
    φ ∈ hullWeb f U (res σ k) ↔ ∀ i < k, φ ∈ polar 𝕜 (f i '' U i (σ i)) := by
  induction k with
  | zero => simp [hullWeb]
  | succ k ih =>
    rw [res_succ, hullWeb_cons, mem_inter_iff, ih, res_length]
    refine ⟨fun h i hi ↦ ?_, fun h ↦ ⟨fun i hi ↦ h i (Nat.lt_succ_of_lt hi), h k k.lt_succ_self⟩⟩
    rcases Nat.lt_succ_iff_lt_or_eq.mp hi with hi | rfl
    · exact h.1 i hi
    · exact h.2

omit [∀ n, TopologicalSpace (X n)] [Module ℝ F] [IsScalarTower ℝ 𝕜 F] in
/-- The sets of the web on the dual of a hull are `ℝ`-convex. -/
theorem convex_hullWeb (l : List ℕ) : Convex ℝ (hullWeb f U l) := by
  induction l with
  | nil => exact convex_univ
  | cons m l ih => exact ih.inter (LinearMap.convex_polar _ _)

omit [∀ n, TopologicalSpace (X n)] [Module ℝ F] [IsScalarTower ℝ 𝕜 F] in
/-- The sets of the web on the dual of a hull are balanced. -/
theorem balanced_hullWeb (l : List ℕ) : Balanced 𝕜 (hullWeb f U l) := by
  induction l with
  | nil => exact balanced_univ
  | cons m l ih => exact ih.inter (LinearMap.balanced_polar _ _)

omit [∀ n, TopologicalSpace (X n)] [Module ℝ F] [IsScalarTower ℝ 𝕜 F] in
/-- The sets of the web on the dual of a hull are closed in the strong dual. -/
theorem isClosed_hullWeb [ContinuousSMul 𝕜 F] (l : List ℕ) : IsClosed (hullWeb f U l) := by
  induction l with
  | nil => exact isClosed_univ
  | cons m l ih => exact ih.inter (StrongDual.isClosed_polar _)

variable [∀ n, IsTopologicalAddGroup (X n)] [∀ n, ContinuousSMul 𝕜 (X n)]
  [IsTopologicalAddGroup F] [ContinuousSMul 𝕜 F]

/-- **The strong dual of a countable locally convex hull of first-countable spaces is strictly
webbed**, Köthe II §35.4.(13). In particular the strong dual of an LF space is strictly webbed. -/
theorem strictlyWebbedSpace_of_locallyConvexFinalTopology [∀ n, FirstCountableTopology (X n)]
    (hF : (inferInstance : TopologicalSpace F) = locallyConvexFinalTopology f)
    (hspan : ⨆ n, LinearMap.range (f n) = ⊤) : StrictlyWebbedSpace 𝕜 (StrongDual 𝕜 F) := by
  have hfcont (n : ℕ) : Continuous (f n) := by
    have h := locallyConvexFinalTopology.continuous_apply f n
    rwa [← hF] at h
  choose U hU using fun n ↦ (𝓝 (0 : X n)).exists_antitone_basis
  -- The family is a web: a continuous functional is bounded by one on some `f k (U k m)`.
  have hweb : IsWeb (hullWeb f U) :=
    { nil := rfl
      iUnion_cons := fun l ↦ by
        refine Subset.antisymm (iUnion_subset fun m ↦ inter_subset_left) fun φ hφ ↦ ?_
        have hnhds : {z : X l.length | ‖φ (f l.length z)‖ ≤ 1} ∈ 𝓝 (0 : X l.length) := by
          have hc : ContinuousAt (fun z ↦ ‖φ (f l.length z)‖) 0 :=
            (continuous_norm.comp (φ.continuous.comp (hfcont l.length))).continuousAt
          exact hc.preimage_mem_nhds (Iic_mem_nhds (by simp))
        obtain ⟨m, -, hm⟩ := (hU l.length).toHasBasis.mem_iff.mp hnhds
        refine mem_iUnion.mpr ⟨m, hφ, ?_⟩
        rintro _ ⟨z, hz, rfl⟩
        exact hm hz }
  -- The web is completing, by the criterion with Banach disks.
  have hcompleting : IsCompletingWeb (hullWeb f U) := by
    refine hweb.isCompletingWeb_of_isBanachDisk (𝕜 := 𝕜) fun σ ↦
      ⟨fun _ ↦ 1, fun _ ↦ one_pos, fun x hx ↦ ?_⟩
    -- Neighbourhoods `V i` on which all `x k` are bounded by one.
    let V : ∀ i, Set (X i) := fun i ↦
      U i (σ i) ∩ ⋂ k ∈ Finset.range i, {z | ‖x k (f i z)‖ ≤ 1}
    have hV (i : ℕ) : V i ∈ 𝓝 (0 : X i) := by
      refine inter_mem ((hU i).mem (σ i)) ((Filter.biInter_finset_mem _).mpr fun k _ ↦ ?_)
      have hc : ContinuousAt (fun z ↦ ‖x k (f i z)‖) 0 :=
        (continuous_norm.comp ((x k).continuous.comp (hfcont i))).continuousAt
      exact hc.preimage_mem_nhds (Iic_mem_nhds (by simp))
    let S : Set F := ⋃ i, f i '' V i
    -- The disk hull of `S` is a neighbourhood of zero in the hull `F`.
    have hspanS : Submodule.span 𝕜 S = ⊤ := by
      refine eq_top_iff.mpr (hspan ▸ iSup_le fun i ↦ ?_)
      rintro _ ⟨z, rfl⟩
      obtain ⟨c, hc⟩ := ((absorbent_nhds_zero (𝕜 := 𝕜) (hV i)) z).exists
      obtain ⟨w, hw, hwz⟩ := hc (mem_singleton z)
      have hwz' : c • w = z := hwz
      rw [← hwz', map_smul]
      exact Submodule.smul_mem _ c
        (Submodule.subset_span (mem_iUnion.mpr ⟨i, w, hw, rfl⟩))
    have hW : diskHull 𝕜 S ∈ 𝓝 (0 : F) := by
      have h := locallyConvexFinalTopology.mem_nhds_zero f (convex_diskHull S)
        (balanced_diskHull S) (absorbent_diskHull_of_span_eq_top 𝕜 S hspanS) fun i ↦
          mem_of_superset (hV i) fun z hz ↦
            subset_diskHull S (mem_iUnion.mpr ⟨i, z, hz, rfl⟩)
      rwa [← hF] at h
    refine ⟨polar 𝕜 (diskHull 𝕜 S), StrongDual.isBanachDisk_polar_of_mem_nhds hW, fun k ↦ ?_⟩
    rw [one_smul, StrongDual.polar_diskHull]
    rintro _ hy
    obtain ⟨i, z, hz, rfl⟩ := mem_iUnion.mp hy
    rcases lt_or_ge k i with hki | hik
    · exact (mem_iInter₂.mp hz.2 k (Finset.mem_range.mpr hki) :)
    · exact (mem_hullWeb_res f U).mp (hx k) i (Nat.lt_succ_of_le hik) _ ⟨z, hz.1, rfl⟩
  -- The sets are convex, balanced and closed, so the web is strict.
  exact ⟨hullWeb f U, hcompleting.isStrictWeb_of_isSeqClosed (convex_hullWeb f U)
    (balanced_hullWeb f U) fun l ↦ (isClosed_hullWeb f U l).isSeqClosed⟩

end StrongDual
